name: CI

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  verify:
    uses: ddtcorex/.github/.github/workflows/node-plugin.yml@f02a7fb6d7a681716e0b2a883f48971e8f318813
