import { fetchMrDetail, fetchMrChanges } from './gitlab-fetch.js'
import type { RunnerConfig } from './cli.js'
import { normalize as posixNormalize } from 'node:path/posix'

// ——— Copied helpers from src/host/orchestrator.ts (standalone for runner, no host transitive) ———
// TODO: extract to shared host-free module src/runner/orchestrator-helpers.ts used by both host and runner

export function buildReviewComment(opts: {
  projectPath: string
  mrIid: number
  gitlabBaseUrl: string
  mode: string
  profile?: string
  summary: string
  failures: string[]
  findings?: { newCount: number; replyCount: number }
  durationMs?: number
  isDiffOnly?: boolean
  isDiscussion?: boolean
}): string {
  const mrUrl = `${opts.gitlabBaseUrl.replace(/\/$/, '')}/${opts.projectPath}/-/merge_requests/${opts.mrIid}`
  const title = opts.isDiffOnly === true ? '## 🤖 Maestro Review — Diff-only' : '## 🤖 Maestro Review'
  const metaBits: string[] = []
  metaBits.push(`**\`${opts.projectPath}\` !${opts.mrIid}**`)
  metaBits.push('✅ Completed')
  metaBits.push(`\`${opts.mode}\``)
  if (opts.profile !== undefined) metaBits.push(`\`${opts.profile}\``)
  if (opts.durationMs !== undefined && opts.durationMs > 0) {
    const s = Math.round(opts.durationMs / 1000)
    metaBits.push(s < 60 ? `${s}s` : `${Math.floor(s / 60)}m ${s % 60}s`)
  }
  const metaLine = metaBits.join(' · ')
  const scopeNote = opts.isDiffOnly === true
    ? '> **Scope:** Diff-only — reviewed the GitLab diff without a local checkout, Magento environment, static analysis, or tests. For a full review, add this project in Settings → Maestro and mention again.\n\n'
    : ''
  const findingsLine = opts.findings !== undefined
    ? (() => {
        const parts: string[] = []
        if (opts.findings.newCount > 0) parts.push(`💬 ${opts.findings.newCount} new`)
        if (opts.findings.replyCount > 0) parts.push(`🔁 ${opts.findings.replyCount} updated`)
        if (parts.length === 0) parts.push('no inline findings')
        return `\n\n**Findings:** ${parts.join(' · ')}`
      })()
    : ''
  const failuresBlock = opts.failures.length > 0
    ? `\n\n<details>\n<summary>⚠️ Failed to post (${opts.failures.length})</summary>\n\n${opts.failures.map((f) => `- \`${f}\``).join('\n')}\n\n</details>`
    : ''
  const footer = `\n\n---\n\n<sub>Generated by Maestro · [View MR →](${mrUrl})</sub>`
  return `${title}\n\n${metaLine}\n\n${scopeNote}${opts.summary}${findingsLine}${failuresBlock}${footer}`
}

interface GitlabMrChange { old_path: string; new_path: string; diff: string; collapsed?: boolean; too_large?: boolean }
interface GitlabDiffPosition { oldLine?: number; newLine?: number }
interface GitlabDiffSnapshot { diffRefs: { base_sha: string; start_sha: string; head_sha: string }; changes: GitlabMrChange[] }

export function diffPositionForNewLine(diff: string, targetLine: number): GitlabDiffPosition | undefined {
  let oldLine = 0; let newLine = 0
  for (const row of diff.split('\n')) {
    const header = /^@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@/.exec(row)
    if (header !== null) { oldLine = Number(header[1]); newLine = Number(header[2]); continue }
    if (row.startsWith('\\')) continue
    if (row.startsWith('+')) { if (newLine === targetLine) return { newLine }; newLine++; continue }
    if (row.startsWith('-')) { oldLine++; continue }
    if (row.startsWith(' ')) { if (newLine === targetLine) return { oldLine, newLine }; oldLine++; newLine++ }
  }
  return undefined
}

function normalizedDiffPath(path: string): string { return posixNormalize(path) }

async function loadLatestDiffSnapshot(fetcher: typeof fetch, apiBase: string, headers: Record<string, string>): Promise<GitlabDiffSnapshot> {
  const versionsResponse = await fetcher(`${apiBase}/versions`, { headers })
  if (!versionsResponse.ok) throw new Error(`GitLab API error ${versionsResponse.status}: ${await versionsResponse.text()}`)
  const versions = await versionsResponse.json() as Array<{ id?: number }>
  const latest = versions[0]
  if (latest?.id === undefined) throw new Error('GitLab merge request has no available diff version')
  const versionResponse = await fetcher(`${apiBase}/versions/${latest.id}`, { headers })
  if (!versionResponse.ok) throw new Error(`GitLab API error ${versionResponse.status}: ${await versionResponse.text()}`)
  const version = await versionResponse.json() as { base_commit_sha?: string; start_commit_sha?: string; head_commit_sha?: string; diffs?: GitlabMrChange[] }
  if (version.base_commit_sha === undefined || version.start_commit_sha === undefined || version.head_commit_sha === undefined) throw new Error('GitLab merge request diff version has incomplete SHA references')
  if (version.diffs === undefined) throw new Error('GitLab merge request diff version has no file diffs')
  return { diffRefs: { base_sha: version.base_commit_sha, start_sha: version.start_commit_sha, head_sha: version.head_commit_sha }, changes: version.diffs }
}

export interface GitlabFindingPoster { baseUrl: string; token: string; projectId: number; mrIid: number; fetcher?: typeof fetch; snapshot?: Promise<GitlabDiffSnapshot> }
export type ReviewFinding = { status: 'new' | 'reply'; body: string; path?: string; line?: number; discussionId?: string }

export async function postReviewFindings(findings: ReviewFinding[], config: GitlabFindingPoster): Promise<void> {
  const fetcher = config.fetcher ?? fetch
  const apiBase = `${config.baseUrl}/api/v4/projects/${config.projectId}/merge_requests/${config.mrIid}`
  const headers = { 'PRIVATE-TOKEN': config.token, 'Content-Type': 'application/json' }
  for (const finding of findings) {
    let response: Response
    if (finding.status === 'reply') {
      if (finding.discussionId === undefined) throw new Error('reply finding missing discussionId')
      response = await fetcher(`${apiBase}/discussions/${encodeURIComponent(finding.discussionId)}/notes`, { method: 'POST', headers, body: JSON.stringify({ body: finding.body }) })
    } else {
      if (finding.path === undefined || finding.line === undefined) throw new Error('new finding missing path or line')
      config.snapshot ??= loadLatestDiffSnapshot(fetcher, apiBase, headers)
      const snapshot = await config.snapshot
      const requestedPath = normalizedDiffPath(finding.path)
      const change = snapshot.changes.find(candidate => normalizedDiffPath(candidate.new_path) === requestedPath)
        ?? snapshot.changes.find(candidate => normalizedDiffPath(candidate.old_path) === requestedPath)
      if (change === undefined) throw new Error(`cannot post inline finding at ${finding.path}:${finding.line}: file is not in the current MR diff`)
      if (change.collapsed === true || change.too_large === true || change.diff === '') throw new Error(`cannot post inline finding at ${finding.path}:${finding.line}: GitLab did not return this file's complete diff`)
      const linePosition = diffPositionForNewLine(change.diff, finding.line)
      if (linePosition === undefined) {
        response = await fetcher(`${apiBase}/notes`, { method: 'POST', headers, body: JSON.stringify({ body: `**Inline fallback — \`${finding.path}:${finding.line}\` line is not in current MR diff**\n\n${finding.body}` }) })
      } else {
        response = await fetcher(`${apiBase}/discussions`, { method: 'POST', headers, body: JSON.stringify({ body: finding.body, position: { position_type: 'text', ...snapshot.diffRefs, old_path: change.old_path, new_path: change.new_path, ...linePosition.oldLine === undefined ? {} : { old_line: linePosition.oldLine }, ...linePosition.newLine === undefined ? {} : { new_line: linePosition.newLine } } }) })
      }
    }
    if (!response.ok) throw new Error(`GitLab API error ${response.status}: ${await response.text()}`)
  }
}

// ——— Runner orchestrator ———

export async function runOnce(cfg: RunnerConfig, deps: {
  fetcher?: typeof fetch; postComment?: (body:string)=>Promise<void>;
  postFindings?: typeof postReviewFindings;
  createAgent?: (cfg: RunnerConfig, changes: unknown)=>Promise<{findings:any[]; summary:string}>
} = {}) {
  const t0 = Date.now()
  const fetcher = deps.fetcher ?? fetch
  const detail = await fetchMrDetail(cfg, fetcher)
  const changes = await fetchMrChanges(cfg, fetcher)
  const raw = deps.createAgent
    ? await deps.createAgent(cfg, changes)
    : { findings: [], summary: `Diff-only review for !${cfg.mrIid}: ${changes.changes.length} file(s)` }
  // Normalize: brief test mock returns {summary, failures} without findings — tolerate both shapes
  const agentResult = { summary: (raw as any).summary ?? '', findings: (raw as any).findings ?? [] }
  const failures: string[] = []
  const doPostFindings = deps.postFindings ?? postReviewFindings
  if (!cfg.dryRun && agentResult.findings.length > 0) {
    try {
      await doPostFindings(agentResult.findings, { baseUrl: cfg.gitlabBaseUrl, token: cfg.gitlabToken, projectId: cfg.sourceProjectId, mrIid: cfg.mrIid, fetcher } as any)
    } catch (e) { failures.push(String(e)) }
  }
  const comment = buildReviewComment({ projectPath: `project/${cfg.sourceProjectId}`, mrIid: cfg.mrIid, gitlabBaseUrl: cfg.gitlabBaseUrl, mode: cfg.mode, summary: agentResult.summary, failures, durationMs: Date.now() - t0, isDiffOnly: true })
  if (!cfg.dryRun && deps.postComment) await deps.postComment(comment).catch(e => failures.push(String(e)))
  const headSha = (detail as any).headSha ?? (detail as any).sha ?? 'unknown'
  return { summary: agentResult.summary, failures, durationMs: Date.now() - t0, headSha }
}
